// data/courses.js
function toSlug(title) {
  return title.toLowerCase().replace(/ /g, "-").replace(/[^a-z0-9-]/g, "");
}
import {
  Code,
  PenTool,
  BarChart2,
  Database,
  Camera,
  Brush,
  Music,
  Globe,
  Bot,
  Shield,
  Home,
  Heart,
  User,
  GraduationCap,
  Globe2,
  DollarSign,
  Lightbulb,
  PenBoxIcon,
  Video,
  Rocket,
  EuroIcon,
} from "lucide-react";

import { Search, BookOpen, Award } from "lucide-react";
export const courses = [
  {
    id: 1,
    title: "Web Development",
    courseCount: "88,000",
    icon: Code,
  },
  {
    id: 2,
    title: "Graphic Design",
    courseCount: "35,000",
    icon: Brush,
  },
  {
    id: 3,
    title: "Digital Marketing",
    courseCount: "41,500",
    icon: BarChart2,
  },
  {
    id: 4,
    title: "Data Science",
    courseCount: "50,000",
    icon: Database,
  },
  {
    id: 5,
    title: "Photography",
    courseCount: "22,000",
    icon: Camera,
  },
  {
    id: 6,
    title: "Music & Audio",
    courseCount: "14,300",
    icon: Music,
  },
  {
    id: 7,
    title: "Writing & Content",
    courseCount: "27,000",
    icon: PenTool,
  },
  {
    id: 8,
    title: "Language Learning",
    courseCount: "19,800",
    icon: Globe,
  },
  {
    id: 9,
    title: "AI & Machine Learning",
    courseCount: "33,700",
    icon: Bot,
  },
  {
    id: 10,
    title: "Cyber Security",
    courseCount: "17,400",
    icon: Shield,
  },
];
export const languages = [
  { code: "en", name: "English" },
  { code: "fr", name: "Français" },
];


export const coursesData = [
  {
    "id": 1,
    "title": "AI Governance & Ethics",
    "instructor": "Dr. Rebecca Lin",
    "category": "AI Tracks",
    "slug": "ai-governance-ethics",
    "level": "Intermediate",
    "rating": 4.7,
    "students": 47000,
    "price": 54.99,
    "duration": "12h",
    "description": "Learn about responsible AI deployment, fairness, transparency, and governance.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": false,
    "isTop": true,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Ethics", "AI", "Governance"],
    "language": "English",
    "subtitles": ["English", "Spanish"],
    "updatedAt": "2025-04-05",
    "videoPreviewUrl": "https://youtu.be/sample1"
  },
  {
    "id": 2,
    "title": "AI in Business Contexts",
    "instructor": "Mark Stevenson",
    "category": "AI Tracks",
    "slug": "ai-in-business-contexts",
    "level": "Intermediate",
    "rating": 4.6,
    "students": 56000,
    "price": 58.99,
    "duration": "14h",
    "description": "Understand AI applications for decision-making, automation, and strategy.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": false,
    "bestseller": true,
    "isTop": false,
    "isPopular": true,
    "isNew": false,
    "isTrending": false,
    "isRecommended": true,
    "tags": ["Business AI", "Decision Making"],
    "language": "English",
    "subtitles": ["French"],
    "updatedAt": "2025-02-21",
    "videoPreviewUrl": "https://youtu.be/sample2"
  },
  {
    "id": 3,
    "title": "Neural Network Architectures",
    "instructor": "Sophie Chan",
    "category": "AI Tracks",
    "slug": "neural-network-architectures",
    "level": "Advanced",
    "rating": 4.8,
    "students": 72000,
    "price": 69.99,
    "duration": "20h",
    "description": "Explore CNNs, RNNs, and transformer architectures with hands-on projects.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": true,
    "isTop": true,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Neural Networks", "Deep Learning", "Transformers"],
    "language": "English",
    "subtitles": ["Spanish", "German"],
    "updatedAt": "2025-03-25",
    "videoPreviewUrl": "https://youtu.be/sample3"
  },
  {
    "id": 4,
    "title": "AI in Academia",
    "instructor": "Dr. Clara Mitchell",
    "category": "Specialized AI Training",
    "slug": "ai-in-academia",
    "level": "Intermediate",
    "rating": 4.4,
    "students": 34000,
    "price": 45.99,
    "duration": "12h",
    "description": "Use AI tools to enhance teaching, learning, and academic assessment.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": false,
    "bestseller": false,
    "isTop": false,
    "isPopular": true,
    "isNew": true,
    "isTrending": false,
    "isRecommended": true,
    "tags": ["AI", "Education", "Adaptive Learning"],
    "language": "English",
    "subtitles": ["English"],
    "updatedAt": "2025-04-10",
    "videoPreviewUrl": "https://youtu.be/sample4"
  },
  {
    "id": 5,
    "title": "Digital Leadership Essentials",
    "instructor": "Tom Bradley",
    "category": "Tech Leadership",
    "slug": "digital-leadership-essentials",
    "level": "Executive",
    "rating": 4.9,
    "students": 15000,
    "price": 119.99,
    "duration": "32h",
    "description": "Lead your organization's digital strategy with confidence and clarity.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": true,
    "isTop": true,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Leadership", "Digital Strategy", "AI"],
    "language": "English",
    "subtitles": ["English", "French"],
    "updatedAt": "2025-03-30",
    "videoPreviewUrl": "https://youtu.be/sample5"
  },
  {
    "id": 6,
    "title": "Machine Learning Fundamentals",
    "instructor": "Dr. James Wilson",
    "category": "AI Tracks",
    "slug": "machine-learning-fundamentals",
    "level": "Beginner",
    "rating": 4.5,
    "students": 89000,
    "price": 49.99,
    "duration": "16h",
    "description": "Master the basics of machine learning algorithms and their applications.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": true,
    "isTop": true,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Machine Learning", "AI", "Data Science"],
    "language": "English",
    "subtitles": ["English", "Spanish", "French"],
    "updatedAt": "2025-01-15",
    "videoPreviewUrl": "https://youtu.be/sample6"
  },
  {
    "id": 7,
    "title": "AI for Healthcare",
    "instructor": "Dr. Sarah Chen",
    "category": "Specialized AI Training",
    "slug": "ai-for-healthcare",
    "level": "Advanced",
    "rating": 4.8,
    "students": 42000,
    "price": 79.99,
    "duration": "24h",
    "description": "Explore AI applications in healthcare, from diagnosis to treatment planning.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": false,
    "isTop": true,
    "isPopular": true,
    "isNew": true,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Healthcare", "AI", "Medical Technology"],
    "language": "English",
    "subtitles": ["English", "German"],
    "updatedAt": "2025-04-01",
    "videoPreviewUrl": "https://youtu.be/sample7"
  },
  {
    "id": 8,
    "title": "Data Science Bootcamp",
    "instructor": "Michael Rodriguez",
    "category": "Data Science",
    "slug": "data-science-bootcamp",
    "level": "Intermediate",
    "rating": 4.7,
    "students": 65000,
    "price": 89.99,
    "duration": "40h",
    "description": "Comprehensive training in data analysis, visualization, and machine learning.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": true,
    "isTop": true,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Data Science", "Python", "Machine Learning"],
    "language": "English",
    "subtitles": ["English", "Spanish"],
    "updatedAt": "2025-02-28",
    "videoPreviewUrl": "https://youtu.be/sample8"
  },
  {
    "id": 9,
    "title": "AI Product Management",
    "instructor": "Dr. Emily Parker",
    "category": "Tech Leadership",
    "slug": "ai-product-management",
    "level": "Intermediate",
    "rating": 4.6,
    "students": 28000,
    "price": 69.99,
    "duration": "18h",
    "description": "Learn to manage AI product development from concept to deployment.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": false,
    "bestseller": false,
    "isTop": false,
    "isPopular": true,
    "isNew": true,
    "isTrending": false,
    "isRecommended": true,
    "tags": ["Product Management", "AI", "Strategy"],
    "language": "English",
    "subtitles": ["English"],
    "updatedAt": "2025-04-15",
    "videoPreviewUrl": "https://youtu.be/sample9"
  },
  {
    "id": 10,
    "title": "Deep Learning Specialization",
    "instructor": "David Kumar",
    "category": "AI Tracks",
    "slug": "deep-learning-specialization",
    "level": "Advanced",
    "rating": 4.9,
    "students": 45000,
    "price": 99.99,
    "duration": "36h",
    "description": "Master deep learning techniques and build complex neural networks.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": true,
    "isTop": true,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Deep Learning", "Neural Networks", "AI"],
    "language": "English",
    "subtitles": ["English", "Spanish", "French"],
    "updatedAt": "2025-03-10",
    "videoPreviewUrl": "https://youtu.be/sample10"
  },
  {
    "id": 11,
    "title": "AI for Finance",
    "instructor": "Dr. Rebecca Lin",
    "category": "Specialized AI Training",
    "slug": "ai-for-finance",
    "level": "Advanced",
    "rating": 4.7,
    "students": 38000,
    "price": 84.99,
    "duration": "20h",
    "description": "Apply AI and machine learning to financial analysis and trading.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": false,
    "isTop": true,
    "isPopular": true,
    "isNew": true,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Finance", "AI", "Trading"],
    "language": "English",
    "subtitles": ["English", "German"],
    "updatedAt": "2025-04-20",
    "videoPreviewUrl": "https://youtu.be/sample11"
  },
  {
    "id": 12,
    "title": "Natural Language Processing",
    "instructor": "Sophie Chan",
    "category": "AI Tracks",
    "slug": "natural-language-processing",
    "level": "Intermediate",
    "rating": 4.6,
    "students": 52000,
    "price": 64.99,
    "duration": "16h",
    "description": "Learn to process and analyze text data using modern NLP techniques.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": false,
    "bestseller": true,
    "isTop": false,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["NLP", "AI", "Text Processing"],
    "language": "English",
    "subtitles": ["English", "Spanish"],
    "updatedAt": "2025-02-15",
    "videoPreviewUrl": "https://youtu.be/sample12"
  },
  {
    "id": 13,
    "title": "AI Ethics & Bias",
    "instructor": "Dr. Clara Mitchell",
    "category": "AI Tracks",
    "slug": "ai-ethics-bias",
    "level": "Intermediate",
    "rating": 4.5,
    "students": 29000,
    "price": 49.99,
    "duration": "12h",
    "description": "Understand and address ethical challenges and biases in AI systems.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": false,
    "bestseller": false,
    "isTop": false,
    "isPopular": true,
    "isNew": true,
    "isTrending": false,
    "isRecommended": true,
    "tags": ["Ethics", "AI", "Bias"],
    "language": "English",
    "subtitles": ["English"],
    "updatedAt": "2025-04-25",
    "videoPreviewUrl": "https://youtu.be/sample13"
  },
  {
    "id": 14,
    "title": "Computer Vision Fundamentals",
    "instructor": "Mark Stevenson",
    "category": "AI Tracks",
    "slug": "computer-vision-fundamentals",
    "level": "Intermediate",
    "rating": 4.7,
    "students": 41000,
    "price": 69.99,
    "duration": "18h",
    "description": "Master image processing and computer vision techniques using AI.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": true,
    "isTop": true,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Computer Vision", "AI", "Image Processing"],
    "language": "English",
    "subtitles": ["English", "French"],
    "updatedAt": "2025-03-05",
    "videoPreviewUrl": "https://youtu.be/sample14"
  },
  {
    "id": 15,
    "title": "AI Project Management",
    "instructor": "Tom Bradley",
    "category": "Tech Leadership",
    "slug": "ai-project-management",
    "level": "Intermediate",
    "rating": 4.6,
    "students": 25000,
    "price": 59.99,
    "duration": "14h",
    "description": "Learn to manage AI projects effectively from planning to deployment.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": false,
    "bestseller": false,
    "isTop": false,
    "isPopular": true,
    "isNew": true,
    "isTrending": false,
    "isRecommended": true,
    "tags": ["Project Management", "AI", "Leadership"],
    "language": "English",
    "subtitles": ["English", "Spanish"],
    "updatedAt": "2025-04-30",
    "videoPreviewUrl": "https://youtu.be/sample15"
  },
  {
    "id": 16,
    "title": "Reinforcement Learning",
    "instructor": "Dr. James Wilson",
    "category": "AI Tracks",
    "slug": "reinforcement-learning",
    "level": "Advanced",
    "rating": 4.8,
    "students": 32000,
    "price": 79.99,
    "duration": "24h",
    "description": "Master reinforcement learning algorithms and their applications.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": true,
    "isTop": true,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Reinforcement Learning", "AI", "Machine Learning"],
    "language": "English",
    "subtitles": ["English", "German"],
    "updatedAt": "2025-02-10",
    "videoPreviewUrl": "https://youtu.be/sample16"
  },
  {
    "id": 17,
    "title": "AI for Marketing",
    "instructor": "Dr. Sarah Chen",
    "category": "Specialized AI Training",
    "slug": "ai-for-marketing",
    "level": "Intermediate",
    "rating": 4.5,
    "students": 36000,
    "price": 54.99,
    "duration": "16h",
    "description": "Leverage AI for marketing analytics, personalization, and automation.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": false,
    "bestseller": false,
    "isTop": false,
    "isPopular": true,
    "isNew": true,
    "isTrending": false,
    "isRecommended": true,
    "tags": ["Marketing", "AI", "Analytics"],
    "language": "English",
    "subtitles": ["English", "French"],
    "updatedAt": "2025-04-15",
    "videoPreviewUrl": "https://youtu.be/sample17"
  },
  {
    "id": 18,
    "title": "AI Security & Privacy",
    "instructor": "Michael Rodriguez",
    "category": "AI Tracks",
    "slug": "ai-security-privacy",
    "level": "Advanced",
    "rating": 4.7,
    "students": 28000,
    "price": 69.99,
    "duration": "20h",
    "description": "Learn to secure AI systems and protect user privacy.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": true,
    "isTop": true,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Security", "Privacy", "AI"],
    "language": "English",
    "subtitles": ["English", "Spanish"],
    "updatedAt": "2025-03-20",
    "videoPreviewUrl": "https://youtu.be/sample18"
  },
  {
    "id": 19,
    "title": "AI for Manufacturing",
    "instructor": "Dr. Emily Parker",
    "category": "Specialized AI Training",
    "slug": "ai-for-manufacturing",
    "level": "Intermediate",
    "rating": 4.6,
    "students": 22000,
    "price": 59.99,
    "duration": "16h",
    "description": "Implement AI solutions for manufacturing optimization and automation.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": false,
    "bestseller": false,
    "isTop": false,
    "isPopular": true,
    "isNew": true,
    "isTrending": false,
    "isRecommended": true,
    "tags": ["Manufacturing", "AI", "Automation"],
    "language": "English",
    "subtitles": ["English"],
    "updatedAt": "2025-04-25",
    "videoPreviewUrl": "https://youtu.be/sample19"
  },
  {
    "id": 20,
    "title": "AI Research Methods",
    "instructor": "David Kumar",
    "category": "AI Tracks",
    "slug": "ai-research-methods",
    "level": "Advanced",
    "rating": 4.8,
    "students": 18000,
    "price": 89.99,
    "duration": "28h",
    "description": "Master research methodologies and experimental design in AI.",
    "image": "https://effvision.com/wp-content/uploads/2024/06/artificial-intelligence-new-technology-science-futuristic-abstract-human-brain-ai-technology-cpu-central-processor-unit-chipset-big-data-machine-learning-cyber-mind-domination-generative-ai-scaled-1.jpg",
    "isFeatured": true,
    "bestseller": true,
    "isTop": true,
    "isPopular": true,
    "isNew": false,
    "isTrending": true,
    "isRecommended": true,
    "tags": ["Research", "AI", "Methodology"],
    "language": "English",
    "subtitles": ["English", "Spanish", "French"],
    "updatedAt": "2025-02-28",
    "videoPreviewUrl": "https://youtu.be/sample20"
  }
];

// ... rest of the existing code ...

const categoriesData = [
  {
    name: "Development",
    slug: "development",
    subcategories: [
      { name: "Web Development", slug: "web-development" },
      { name: "Mobile Development", slug: "mobile-development" },
      { name: "Game Development", slug: "game-development" },
      { name: "Database Design", slug: "database-design" },
      { name: "Software Testing", slug: "software-testing" },
    ],
  },
  {
    name: "IT Support",
    slug: "it-support",
    subcategories: [
      { name: "Network Administration", slug: "network-administration" },
      { name: "Cybersecurity", slug: "cybersecurity" },
      { name: "Cloud Computing", slug: "cloud-computing" },
      { name: "System Administration", slug: "system-administration" },
    ],
  },
  {
    name: "Data Science",
    slug: "data-science",
    subcategories: [
      { name: "Machine Learning", slug: "machine-learning" },
      { name: "Data Analysis", slug: "data-analysis" },
      { name: "Big Data", slug: "big-data" },
      { name: "Artificial Intelligence", slug: "artificial-intelligence" },
    ],
  },
  {
    name: "Design",
    slug: "design",
    subcategories: [
      { name: "UX/UI Design", slug: "ux-ui-design" },
      { name: "Graphic Design", slug: "graphic-design" },
      { name: "Web Design", slug: "web-design" },
      { name: "3D & Animation", slug: "3d-animation" },
    ],
  },
  {
    name: "Business",
    slug: "business",
    subcategories: [
      { name: "Entrepreneurship", slug: "entrepreneurship" },
      { name: "Marketing", slug: "marketing" },
      { name: "Finance", slug: "finance" },
      { name: "Project Management", slug: "project-management" },
    ],
  },
];

export default categoriesData;

export const testimonials = [
  {
    id: 1,
    name: "Alex Johnson",
    role: "Software Developer",
    image: "https://business.appstate.edu/sites/default/files/styles/asu_news_full/public/asu_news/student-profile-javon-nathaniel.jpg?itok=-KyYkUKf",
    content:
      "LearnHub completely transformed my career. I went from knowing nothing about coding to landing a job as a full-stack developer in just 6 months.",
    rating: 5,
  },
  {
    id: 2,
    name: "Maria Garcia",
    role: "UX Designer",
    image: "https://www.law.uchicago.edu/sites/default/files/styles/extra_large/public/2018-03/theisen_tarra.jpg?itok=Olm_LKro",
    content:
      "The design courses on LearnHub are exceptional. The instructors are industry professionals who provide real-world insights that you can't get elsewhere.",
    rating: 5,
  },
  {
    id: 3,
    name: "David Kim",
    role: "Data Analyst",
    image: "https://publichealth.uga.edu/wp-content/uploads/2020/01/Thomas-Cameron_Student_Profile.jpg",
    content:
      "The roadmap feature helped me understand exactly what I needed to learn to transition into data science. Highly recommended for career changers!",
    rating: 4,
  },
];

export const howItWorks = [
  {
    id: 1,
    title: "Find Your Course",
    description:
      "Browse our extensive library of courses or use our personalized roadmaps to find the perfect learning path for your goals.",
    icon: Search,
  },
  {
    id: 2,
    title: "Learn at Your Pace",
    description:
      "Access course materials anytime, anywhere. Learn at your own pace with our flexible platform that adapts to your schedule.",
    icon: BookOpen,
  },
  {
    id: 3,
    title: "Earn Certificates",
    description:
      "Complete courses and earn certificates to showcase your new skills to employers and advance your career.",
    icon: Award,
  },
];

export const userRolesCards = [
  {
    role: "Students",
    icon: GraduationCap, // Lucide icon
    features: [
      "Learn at your own pace",
      "Track your progress",
      "Interact with instructors",
      "Earn verified certificates",
    ],
  },
  // {
  //   role: "Lecturers",
  //   icon: "Presentation", // Lucide icon
  //   features: [
  //     "Upload courses easily",
  //     "Engage with students",
  //     "Track student performance",
  //     "Earn revenue from your expertise",
  //   ],
  // },
  // {
  //   role: "Admins",
  //   icon: "ShieldCheck", // Lucide icon
  //   features: [
  //     "Manage users and courses",
  //     "Access detailed analytics",
  //     "Oversee site operations",
  //     "Optimize platform functionality",
  //   ],
  // },
];

export const whyTeach = [
  {
    icon: Globe2, // or use an icon component or image path
    title: "Reach millions of learners",
    description:
      "Connect with over 50 million students worldwide eager to learn from your expertise and experience.",
  },
  {
    icon: EuroIcon,
    title: "Monetize your expertise",
    description:
      "Earn revenue through course sales, subscriptions, and our affiliate program. Our top instructors earn six figures annually.",
  },
  {
    icon: Lightbulb,
    title: "Create lasting impact",
    description:
      "Transform lives through education and build a legacy by sharing your knowledge with eager students around the globe.",
  },
];

export const courseSteps = [
  {
    step: 1,
    icon: PenBoxIcon,
    title: "Plan Your Module",
    description:
      "Define your target audience and outline your curriculum with our planning tools.",
  },
  {
    step: 2,
    icon: Video,
    title: "Create your content",
    description:
      "Record videos, create assignments, and design quizzes with our easy-to-use module builder.",
  },
  {
    step: 3,
    icon: Rocket,
    title: "Publish and promote",
    description:
      "Launch your module and leverage our marketing tools to reach your ideal students.",
  },

  {
    step: 4,
    icon: Rocket,
    title: "Earn and grow",
    description:
      "Get paid for your expertise and expand your module offerings based on student feedback.",
  },
];


export const navMenu = [
  {
    title: "AI Tracks",
    modules: [
      { code: "AI001", name: "Introduction to AI", duration: "2 Weeks", topics: "Foundational concepts, trends in AI research" },
      { code: "AI002", name: "Machine Learning Methodologies", duration: "2 Weeks", topics: "Algorithms, optimization techniques" },
      { code: "AI003", name: "Neural Network Architectures", duration: "2 Weeks", topics: "Frameworks, explored through implementations" },
      { code: "AI005", name: "Advanced NLP", duration: "2 Weeks", topics: "Semantic analysis, conversational AI" },
      { code: "AI006", name: "AI in Business Contexts", duration: "2 Weeks", topics: "AI for decision-making, operational automation" },
      { code: "AI006", name: "AI Governance & Ethics", duration: "2 Weeks", topics: "Best practices in ethical AI deployment" },
      { code: "AI007", name: "Frontier AI", duration: "2 Weeks", topics: "Generative models, quantum computing applications" },
    ],
  },
  {
    title: "Specialized AI Training",
    modules: [
      { code: "SAI001", name: "AI in Healthcare", duration: "2 Weeks", topics: "Diagnostics, patient care, operational efficiency" },
      { code: "SAI002", name: "Financial AI", duration: "2 Weeks", topics: "Fraud detection, risk analysis" },
      { code: "SAI003", name: "Manufacturing Intelligence", duration: "2 Weeks", topics: "Smart factories, process optimization" },
      { code: "SAI004", name: "Retail Analytics", duration: "2 Weeks", topics: "Consumer insights, inventory management" },
      { code: "SAI005", name: "AI in Academia", duration: "2 Weeks", topics: "Advanced pedagogy tools, adaptive learning systems" },
    ],
  },
  {
    title: "Foundation Level",
    modules: [
      { code: "FL001", name: "Data Basics", duration: "2 Weeks", topics: "Data Types, Sources, Quality" },
      { code: "FL002", name: "Visualization Fundamentals", duration: "2 Weeks", topics: "Chart Types, Design Principles" },
      { code: "FL003", name: "Basic Analytics", duration: "2 Weeks", topics: "Simple Calculations, Filters" },
      { code: "FL004", name: "Platform Navigation", duration: "2 Weeks", topics: "Interface Mastery, Settings" },
    ],
  },
  {
    title: "Manufacturing Analytics",
    modules: [
      { code: "MA001", name: "Production Efficiency", duration: "2 Weeks", topics: "OEE, Downtime, Yield" },
      { code: "MA002", name: "Quality Control", duration: "2 Weeks", topics: "Defect Rates, Process Capability" },
      { code: "MA003", name: "Supply Chain", duration: "2 Weeks", topics: "Inventory Turns, Lead Time" },
      { code: "MA004", name: "Maintenance", duration: "2 Weeks", topics: "Equipment Health, Predictive Maintenance" },
    ],
  },
  {
    title: "Advanced Analytics",
    modules: [
      { code: "AA001", name: "Predictive Models", duration: "2 Weeks", topics: "Time Series Analysis, Regression" },
      { code: "AA002", name: "Machine Learning", duration: "2 Weeks", topics: "Classification, Clustering" },
      { code: "AA003", name: "NLP", duration: "2 Weeks", topics: "Text Analytics, Sentiment Analysis" },
      { code: "AA004", name: "Advanced Visualization", duration: "2 Weeks", topics: "Custom Visuals, Animation" },
    ],
  },
  {
    title: "Financial Services Analytics",
    modules: [
      { code: "FA001", name: "Portfolio Analysis", duration: "8–10 Weeks", topics: "Returns, Risk Metrics" },
      { code: "FA002", name: "Customer Profitability", duration: "6–8 Weeks", topics: "Lifetime Value, Product Usage" },
      { code: "FA003", name: "Compliance", duration: "10–12 Weeks", topics: "Exposure, Violations" },
      { code: "FA004", name: "Fraud Detection", duration: "8–10 Weeks", topics: "Transaction Patterns, Anomalies" },
    ],
  },
  {
    title: "Dashboard Development",
    modules: [
      { code: "DDP001", name: "Requirements Gathering", duration: "2–3 Weeks", topics: "Stakeholder Interviews, Use Case Analysis" },
      { code: "DDP002", name: "Design", duration: "3–4 Weeks", topics: "Mockups, User Experience Planning" },
      { code: "DDP003", name: "Development", duration: "4–6 Weeks", topics: "Data Model Creation, Visual Development" },
      { code: "DDP004", name: "Testing & Optimization", duration: "2–3 Weeks", topics: "Performance Testing, User Acceptance" },
    ],
  },
  {
    title: "Executive Development",
    modules: [
      { code: "EDT001", name: "C-Suite", duration: "12 Months", topics: "Strategic Vision, Board Relations" },
      { code: "EDT002", name: "Senior Management", duration: "9 Months", topics: "Operational Excellence, Team Building" },
      { code: "EDT003", name: "Middle Management", duration: "6 Months", topics: "Project Leadership, Change Management" },
      { code: "EDT004", name: "Emerging Leaders", duration: "4 Months", topics: "Foundation Skills, Personal Development" },
    ],
  },
  {
    title: "Tech Leadership",
    modules: [
      { code: "TLE001", name: "Digital Leadership", duration: "16 Weeks", topics: "AI/ML Understanding, Digital Strategy" },
      { code: "TLE002", name: "Engineering Leadership", duration: "20 Weeks", topics: "Technical Project Management, Innovation" },
      { code: "TLE003", name: "Data Leadership", duration: "14 Weeks", topics: "Analytics Strategy, Data Governance" },
      { code: "TLE004", name: "Product Leadership", duration: "18 Weeks", topics: "Product Strategy, Market Analysis" },
    ],
  },
  {
    title: "Sales Training",
    modules: [
      { code: "STL001", name: "Basic Sales", duration: "4 Weeks", topics: "Principles, Product Knowledge" },
      { code: "STL002", name: "Intermediate Sales", duration: "8 Weeks", topics: "Advanced Selling Techniques, Territory Management" },
      { code: "STL003", name: "Advanced Sales", duration: "12 Weeks", topics: "Strategic Account Management, Sales Leadership" },
      { code: "STL004", name: "Expert Sales", duration: "16 Weeks", topics: "Global Sales Strategy, Enterprise Selling" },
    ],
  },
  {
    title: "Sales Development",
    modules: [
      { code: "SD001", name: "Sales Skills", duration: "16 Weeks", topics: "Negotiation, Closing Techniques" },
      { code: "SD002", name: "Marketing Skills", duration: "20 Weeks", topics: "Digital Marketing, Analytics" },
      { code: "SD003", name: "Technical Skills", duration: "14 Weeks", topics: "CRM, Sales Tools" },
      { code: "SD004", name: "Leadership", duration: "18 Weeks", topics: "Team Management, Strategy" },
    ],
  },
  {
    title: "Interim Management",
    modules: [
      { code: "IML001", name: "Executive Leadership", duration: "6–12 Months", topics: "Strategic Direction, Transformation Plans" },
      { code: "IML002", name: "Operational Management", duration: "3–9 Months", topics: "Process Optimization, Team Development" },
      { code: "IML003", name: "Project Leadership", duration: "2–6 Months", topics: "Project Completion, Knowledge Transfer" },
      { code: "IML004", name: "Crisis Management", duration: "1–3 Months", topics: "Stability Restoration, Risk Mitigation" },
    ],
  },
].map(item =>({
  ...item,
  slug: toSlug(item.title)
}));


export const stepsData = [
  {
    id: 1,
    step: "Step 1: Enroll",
    // title: "Choose Your Path",
    description: "Choose a course that fits your interests and goals",
    image: "https://i.imgur.com/tcbXvJS.jpeg",
    bgColor: "bg-orange-100",
    stepBg: "bg-red-500"
  },
  {
    id: 2,
    step: "Step 2: Learn",
    // title: "Engage & Grow",
    description: "Engage with course material, instructors, and peers",
    image: "https://i.imgur.com/6rsA9GM.jpeg",
    bgColor: "bg-blue-100",
    stepBg: "bg-blue-500"
  },
  {
    id: 3,
    step: "Step 3: Interact",
    // title: "Connect & Collaborate",
    description: "Participate in discussions and get certified",
    image: "https://i.imgur.com/TSKcYTY.jpeg",
    bgColor: "bg-green-100",
    stepBg: "bg-green-500"
  },
  {
    id: 4,
    step: "Step 4: Succeed",
    // title: "Achieve Your Goals",
    description: "Earn certificates or revenue from your courses",
    image: "https://i.imgur.com/de4dAU9.jpeg",
    bgColor: "bg-purple-100",
    stepBg: "bg-purple-500"
  }
]
